[project]
name = "viscm"
dynamic = ["version"]
description = "A colormap tool"
readme = "README.rst"
authors = [
  {name = "Nathaniel J. Smith", email = "njs@pobox.com"},
  {name = "Stefan van der Walt", email = "stefanv@berkeley.edu"},
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]

requires-python = ">=3.12"
dependencies = [
  "numpy >=1.26",
  "matplotlib >=3.5",
  "colorspacious >=1.1",
  "scipy >=1.8",
]

[project.optional-dependencies]
# Qt6 was released 2020.08.12
PySide = ["PySide6"]
PyQt = ["PyQt6"]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pytest>=8.4.2",
    "pytest-cov>=7.1.0",
    "pytest-qt>=4.5.0",
    "pytest-xvfb>=3.1.1",
]

[project.urls]
repository = "https://github.com/matplotlib/viscm"
# documentation = "https://viscm.readthedocs.io"

[project.license]
text = "MIT"
files = ["LICENSE"]

[project.scripts]
viscm = "viscm.cli:cli"


[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
zip-safe = false
packages = {find = {}}
package-data = {viscm = ["examples/*"]}


[tool.mypy]
python_version = "3.12"

# These libraries don't have type stubs. Mypy will see them as `Any` and not
# throw an [import] error.
[[tool.mypy.overrides]]
module = [
  "colorspacious",
  "mpl_toolkits.*",
  "scipy.*",
]
ignore_missing_imports = true


[tool.ruff.lint]
select = [
  "F",
  "E",
  "W",
  "C90",
  "I",
  "N",
  "UP",
  "YTT",
  "B",
  "A",
  "C4",
  "T10",
  "RUF",
]
ignore = [
  "B905",
  "UP031",
  "RUF005",
  "RUF046",
  "RUF059",
]

[tool.ruff.lint.per-file-ignores]
"viscm/gui.py" = ["N8"]

[tool.ruff.lint.mccabe]
max-complexity = 11
