name: "Release"
permissions:
  contents: "read"
on:
  release:
    types:
      - "published"

jobs:

  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"  # v7.0.1
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: "actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97"  # v7.0.0
        with:
          python-version: "3.12"

      - name: "Install build tool"
        run: "pip install --user build"

      - name: "Build binary dist (wheel) and source dist"
        run: "python -m build"

      - uses: "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a" # v7.0.1
        with:
          name: "dist"
          path: "dist/"

  pypi-publish:
    name: "Upload dist to PyPI"
    needs: "build"
    runs-on: "ubuntu-latest"
    environment:
      name: "pypi"
      url: "https://pypi.org/p/viscm"
    permissions:
      id-token: "write"
    steps:
      - name: "Get build artifact"
        uses: "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c" # v8.0.1
        with:
          name: "dist"
          path: "dist/"

      - name: "Upload dist to PyPI"
        uses: "pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33" # v1.14.2
