name: "Release"
permissions:
  contents: "read"
on:
  release:
    types:
      - "published"

jobs:

  build-and-release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6.0.2"
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.12"

      - name: "Install build tool"
        run: "pip install --user build"

      - name: "Build binary dist (wheel) and source dist"
        run: "python -m build"

      - name: "Publish to PyPI"
        uses: "pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b" # v1.14.0
        with:
          password: "${{ secrets.PYPI_TOKEN }}"
